const PDFDocument = require("pdfkit");

exports.generatePDF = (title, content, res, username = "Student") => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
    bufferPages: true // 🔥 REQUIRED
  });

  const date = new Date().toLocaleDateString();

  // Headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${title.replace(/\s+/g, "_")}.pdf`
  );

  doc.pipe(res);

  /* ---------- TITLE ---------- */
  doc
    .font("Helvetica-Bold")
    .fontSize(20)
    .text(title, { align: "center" })
    .moveDown(2);

  /* ---------- CONTENT ---------- */
  const lines = content.split("\n");

  lines.forEach((line) => {
    // Code block
    if (line.includes("{") || line.includes("}") || line.includes(";")) {
      doc
        .font("Courier")
        .fontSize(10)
        .text(line, { indent: 20 });
    }
    // Heading
    else if (line === line.toUpperCase() && line.length < 40) {
      doc
        .moveDown()
        .font("Helvetica-Bold")
        .fontSize(14)
        .text(line);
    }
    // Normal text
    else {
      doc
        .font("Helvetica")
        .fontSize(12)
        .text(line, { lineGap: 4 });
    }
  });

  /* ---------- FOOTER (SAFE & CORRECT) ---------- */
  const range = doc.bufferedPageRange(); // { start, count }

  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);

    // Watermark
    doc
      .fontSize(9)
      .fillColor("gray")
      .opacity(0.5)
      .text(
        `Generated for ${username} on ${date}
        Generated by Student Tracker`,
        50,
        doc.page.height - 40,
        { align: "center" }
      )
      .opacity(1);

    // Page number
    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        `Page ${i - range.start + 1} of ${range.count}`,
        50,
        doc.page.height - 20,
        { align: "center" }
      );
  }

  doc.end();
};


// const PDFDocument = require("pdfkit");

// exports.generatePDF = (title, content, res) => {
//   const doc = new PDFDocument({ margin: 50 });

//   // Set response headers
//   res.setHeader("Content-Type", "application/pdf");
//   res.setHeader(
//     "Content-Disposition",
//     `attachment; filename=${title.replace(/\s+/g, "_")}.pdf`
//   );

//   doc.pipe(res);

//   // Title
//   doc
//     .fontSize(20)
//     .text(title, { align: "center" })
//     .moveDown();

//   // Content
//   doc
//     .fontSize(12)
//     .text(content, {
//       align: "left"
//     });

//   doc.end();
// };
