import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BookOpen, Sparkles, Brain, Code, Lightbulb, Download, ArrowLeft, Loader2 } from "lucide-react";
import axios from "../../api/axiosInstance";
import { pdfApi } from "../../api/pdf.api";
import { useNavigate } from "react-router-dom";
import { useTheme } from "../../context/ThemeContext";
import toast from "react-hot-toast";
import ReactMarkdown from "react-markdown";
import { clsx } from "clsx";

const features = [
  { icon: Brain, title: "AI-Powered", desc: "Explanations generated by advanced AI models" },
  { icon: Code, title: "Code Examples", desc: "Get practical code snippets in multiple languages" },
  { icon: Lightbulb, title: "Real Analogies", desc: "Complex concepts explained with simple analogies" },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1, delayChildren: 0.2 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: "spring", stiffness: 100, damping: 15 }
  },
};

export default function LearningContent() {
  const [topic, setTopic] = useState("");
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const navigate = useNavigate();
  const { isDark } = useTheme();

  const generateLearning = async () => {
    if (!topic) return toast.error("Please enter a topic");

    setLoading(true);
    setResult("");
    try {
      const res = await axios.post("/learning/content", {
        topic,
        prompt,
        level: "beginner",
      });
      setResult(res.data.explanation);
      toast.success("Content generated successfully!");
    } catch (err) {
      toast.error("Error generating learning content");
    }
    setLoading(false);
  };

  const downloadPDF = async () => {
    setDownloadingPdf(true);
    try {
      const blob = await pdfApi.downloadNotes(topic, prompt);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${topic}.pdf`;
      a.click();
      window.URL.revokeObjectURL(url);
      toast.success("PDF downloaded!");
    } catch {
      toast.error("Failed to generate PDF");
    }
    setDownloadingPdf(false);
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && e.ctrlKey) generateLearning();
  };

  return (
    <div className={clsx(
      "min-h-screen p-6 md:p-10 transition-colors duration-200",
      isDark
        ? "bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900"
        : "bg-gradient-to-br from-purple-50 via-white to-fuchsia-50"
    )}>
      {/* Back Button */}
      <motion.button
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        whileHover={{ x: -5 }}
        onClick={() => navigate('/learning')}
        className={clsx(
          "flex items-center gap-2 mb-6 group transition-colors",
          isDark ? "text-slate-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
        )}
      >
        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
        <span className="text-sm font-medium">Back to Learning Hub</span>
      </motion.button>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="max-w-4xl mx-auto"
      >
        {/* Header */}
        <motion.div variants={itemVariants} className="mb-10">
          <div className="flex items-center gap-3 mb-4">
            <motion.div
              animate={{ rotate: [0, 360], scale: [1, 1.1, 1] }}
              transition={{ duration: 3, repeat: Infinity }}
              className="p-3 bg-gradient-to-br from-purple-500 to-fuchsia-600 rounded-xl shadow-lg shadow-purple-500/30"
            >
              <Sparkles className="w-6 h-6 text-white" />
            </motion.div>
            <span className={clsx(
              "text-sm font-medium px-3 py-1 rounded-full",
              isDark ? "text-purple-400 bg-purple-900/30" : "text-purple-600 bg-purple-50"
            )}>
              AI-Powered Learning
            </span>
          </div>

          <h1 className={clsx("text-3xl md:text-4xl font-bold mb-3", isDark ? "text-white" : "text-slate-900")}>
            Learning Content
          </h1>
          <p className={clsx("max-w-2xl", isDark ? "text-slate-400" : "text-slate-600")}>
            Enter any topic and get a comprehensive AI-generated explanation with step-by-step
            breakdowns, real-world analogies, and practical code examples.
          </p>
        </motion.div>

        {/* Features Row */}
        <motion.div
          variants={itemVariants}
          className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-10"
        >
          {features.map((feature, index) => (
            <motion.div
              key={index}
              whileHover={{ y: -4, scale: 1.02 }}
              className={clsx(
                "rounded-xl p-4 border shadow-sm hover:shadow-md transition-shadow flex items-start gap-3",
                isDark ? "bg-slate-800 border-slate-700" : "bg-white border-purple-100"
              )}
            >
              <div className={clsx("p-2 rounded-lg", isDark ? "bg-purple-900/30" : "bg-purple-100")}>
                <feature.icon className={clsx("w-5 h-5", isDark ? "text-purple-400" : "text-purple-600")} />
              </div>
              <div>
                <h3 className={clsx("font-semibold text-sm", isDark ? "text-white" : "text-slate-900")}>{feature.title}</h3>
                <p className={clsx("text-xs", isDark ? "text-slate-400" : "text-slate-500")}>{feature.desc}</p>
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* Input Section */}
        <motion.div
          variants={itemVariants}
          className={clsx(
            "rounded-2xl p-6 border shadow-lg mb-8",
            isDark ? "bg-slate-800 border-slate-700" : "bg-white border-slate-200"
          )}
        >
          <div className="space-y-4">
            <div>
              <label className={clsx("block text-sm font-medium mb-2", isDark ? "text-slate-300" : "text-slate-700")}>
                Topic <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <BookOpen className={clsx("absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5", isDark ? "text-slate-500" : "text-slate-400")} />
                <input
                  type="text"
                  placeholder="Enter topic (e.g., Binary Search, Neural Networks...)"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  onKeyPress={handleKeyPress}
                  className={clsx(
                    "w-full pl-12 pr-4 py-4 border rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all",
                    isDark
                      ? "bg-slate-700 border-slate-600 text-white placeholder-slate-400"
                      : "bg-slate-50 border-slate-200 text-slate-900 placeholder-slate-400"
                  )}
                />
              </div>
            </div>

            <div>
              <label className={clsx("block text-sm font-medium mb-2", isDark ? "text-slate-300" : "text-slate-700")}>
                Additional Instructions (Optional)
              </label>
              <textarea
                placeholder="Any specific requirements? (e.g., 'explain with Python examples', 'focus on time complexity'...)"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={3}
                className={clsx(
                  "w-full px-4 py-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all resize-none",
                  isDark
                    ? "bg-slate-700 border-slate-600 text-white placeholder-slate-400"
                    : "bg-slate-50 border-slate-200 text-slate-900 placeholder-slate-400"
                )}
              />
            </div>

            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={generateLearning}
              disabled={loading}
              className="w-full py-4 bg-gradient-to-r from-purple-500 to-fuchsia-600 text-white font-semibold rounded-xl shadow-lg shadow-purple-500/30 hover:shadow-xl hover:shadow-purple-500/40 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                  >
                    <Loader2 className="w-5 h-5" />
                  </motion.div>
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate Explanation
                </>
              )}
            </motion.button>

            <p className={clsx("text-xs text-center", isDark ? "text-slate-500" : "text-slate-400")}>
              Press Ctrl + Enter to generate
            </p>
          </div>
        </motion.div>

        {/* Result Section */}
        <AnimatePresence mode="wait">
          {result && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="space-y-4"
            >
              <div className="flex items-center justify-between">
                <h2 className={clsx("text-xl font-bold flex items-center gap-2", isDark ? "text-white" : "text-slate-900")}>
                  <BookOpen className="w-5 h-5 text-purple-500" />
                  Generated Explanation
                </h2>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={downloadPDF}
                  disabled={downloadingPdf}
                  className="px-4 py-2 bg-gradient-to-r from-emerald-500 to-teal-600 text-white text-sm font-medium rounded-lg shadow-md hover:shadow-lg transition-all flex items-center gap-2 disabled:opacity-50"
                >
                  {downloadingPdf ? (
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    >
                      <Loader2 className="w-4 h-4" />
                    </motion.div>
                  ) : (
                    <Download className="w-4 h-4" />
                  )}
                  Download PDF
                </motion.button>
              </div>

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className={clsx(
                  "rounded-2xl p-6 border shadow-lg prose max-w-none",
                  isDark ? "bg-slate-800 border-slate-700 prose-invert" : "bg-white border-slate-200 prose-slate"
                )}
              >
                <ReactMarkdown
                  components={{
                    h1: ({ node, ...props }) => <h1 className={clsx("text-2xl font-bold mb-4", isDark ? "text-white" : "text-slate-900")} {...props} />,
                    h2: ({ node, ...props }) => <h2 className={clsx("text-xl font-semibold mt-6 mb-3", isDark ? "text-slate-200" : "text-slate-800")} {...props} />,
                    h3: ({ node, ...props }) => <h3 className={clsx("text-lg font-medium mt-4 mb-2", isDark ? "text-slate-300" : "text-slate-700")} {...props} />,
                    p: ({ node, ...props }) => <p className={clsx("leading-relaxed mb-4", isDark ? "text-slate-300" : "text-slate-600")} {...props} />,
                    code: ({ node, inline, ...props }) =>
                      inline ? (
                        <code className={clsx("px-1.5 py-0.5 rounded text-sm", isDark ? "bg-purple-900/30 text-purple-300" : "bg-purple-100 text-purple-800")} {...props} />
                      ) : (
                        <code className="block bg-slate-900 text-green-400 p-4 rounded-lg overflow-x-auto text-sm" {...props} />
                      ),
                    ul: ({ node, ...props }) => <ul className="list-disc list-inside space-y-1 mb-4" {...props} />,
                    ol: ({ node, ...props }) => <ol className="list-decimal list-inside space-y-1 mb-4" {...props} />,
                    li: ({ node, ...props }) => <li className={isDark ? "text-slate-300" : "text-slate-600"} {...props} />,
                  }}
                >
                  {result}
                </ReactMarkdown>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Empty State */}
        {!result && !loading && (
          <motion.div
            variants={itemVariants}
            className="text-center py-12"
          >
            <motion.div
              animate={{ scale: [1, 1.1, 1], rotate: [0, 5, -5, 0] }}
              transition={{ duration: 3, repeat: Infinity }}
              className={clsx("w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6", isDark ? "bg-purple-900/30" : "bg-purple-100")}
            >
              <Brain className={clsx("w-10 h-10", isDark ? "text-purple-400" : "text-purple-500")} />
            </motion.div>
            <h3 className={clsx("text-xl font-semibold mb-2", isDark ? "text-white" : "text-slate-900")}>
              What would you like to learn?
            </h3>
            <p className={clsx("max-w-md mx-auto", isDark ? "text-slate-400" : "text-slate-500")}>
              Enter a topic above and our AI will generate a comprehensive,
              easy-to-understand explanation just for you.
            </p>
          </motion.div>
        )}
      </motion.div>

      {/* Background Decoration */}
      <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
        <div className={clsx(
          "absolute top-20 right-20 w-72 h-72 rounded-full mix-blend-multiply filter blur-3xl animate-pulse",
          isDark ? "bg-purple-900/30 opacity-50" : "bg-purple-200 opacity-30"
        )} />
        <div className={clsx(
          "absolute bottom-20 left-20 w-72 h-72 rounded-full mix-blend-multiply filter blur-3xl animate-pulse",
          isDark ? "bg-fuchsia-900/30 opacity-50" : "bg-fuchsia-200 opacity-30"
        )} style={{ animationDelay: '1s' }} />
      </div>
    </div>
  );
}
