import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BookOpen, Sparkles, Brain, Code, Lightbulb, Download, ArrowLeft, Loader2, Zap } from "lucide-react";
import axios from "../../api/axiosInstance";
import { pdfApi } from "../../api/pdf.api";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import ReactMarkdown from "react-markdown";

const features = [
  { icon: Brain, title: "AI-Powered", desc: "Explanations generated by advanced AI models" },
  { icon: Code, title: "Code Examples", desc: "Get practical code snippets in multiple languages" },
  { icon: Lightbulb, title: "Real Analogies", desc: "Complex concepts explained with simple analogies" },
];

export default function LearningContent() {
  const [topic, setTopic] = useState("");
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const navigate = useNavigate();

  const generateLearning = async () => {
    if (!topic) return toast.error("Please enter a topic");

    setLoading(true);
    setResult("");
    try {
      const res = await axios.post("/learning/content", {
        topic,
        prompt,
        level: "beginner",
      });
      setResult(res.data.explanation);
      toast.success("Content generated successfully!");
    } catch (err) {
      toast.error("Error generating learning content");
    }
    setLoading(false);
  };

  const downloadPDF = async () => {
    setDownloadingPdf(true);
    try {
      const blob = await pdfApi.downloadNotes(topic, prompt);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${topic}.pdf`;
      a.click();
      window.URL.revokeObjectURL(url);
      toast.success("PDF downloaded!");
    } catch {
      toast.error("Failed to generate PDF");
    }
    setDownloadingPdf(false);
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && e.ctrlKey) generateLearning();
  };

  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-10 font-sans">

      {/* Back Button */}
      <button
        onClick={() => navigate('/learning')}
        className="flex items-center gap-2 mb-8 group text-gray-400 hover:text-white transition-colors"
      >
        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
        <span className="text-sm font-medium">Back to Hub</span>
      </button>

      <div className="max-w-5xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

          {/* Left Column: Input (4 cols) */}
          <div className="lg:col-span-4 space-y-6">
            <div className="sticky top-10">
              <div className="mb-6">
                <h1 className="text-3xl font-bold text-white mb-2">AI Explainer</h1>
                <p className="text-gray-400 text-sm leading-relaxed">
                  Ask our AI to break down complex topics into simple, digestible explanations with code and analogies.
                </p>
              </div>

              <div className="bg-[#0A0A0A] border border-[#1F1F1F] rounded-2xl p-6 shadow-xl">
                <div className="space-y-5">
                  <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">
                      Topic
                    </label>
                    <input
                      type="text"
                      placeholder="e.g. Binary Search"
                      value={topic}
                      onChange={(e) => setTopic(e.target.value)}
                      onKeyPress={handleKeyPress}
                      className="w-full px-4 py-3 bg-[#141414] border border-[#1F1F1F] rounded-xl text-white placeholder-gray-600 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all font-medium"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">
                      Specific Focus (Optional)
                    </label>
                    <textarea
                      placeholder="e.g. Focus on Python implementation..."
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      rows={4}
                      className="w-full px-4 py-3 bg-[#141414] border border-[#1F1F1F] rounded-xl text-white placeholder-gray-600 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all resize-none text-sm"
                    />
                  </div>

                  <button
                    onClick={generateLearning}
                    disabled={loading}
                    className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg shadow-blue-900/20"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <Zap className="w-4 h-4" />
                        Generate Content
                      </>
                    )}
                  </button>
                  <p className="text-[10px] text-center text-gray-600">
                    Pro Tip: Use specific keywords for better results.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Output (8 cols) */}
          <div className="lg:col-span-8 min-h-[600px] flex flex-col">
            <AnimatePresence mode="wait">
              {result ? (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="bg-[#0A0A0A] border border-[#1F1F1F] rounded-2xl p-8 md:p-10 relative flex-grow"
                >
                  <div className="absolute top-6 right-6">
                    <button
                      onClick={downloadPDF}
                      disabled={downloadingPdf}
                      className="p-2 text-gray-400 hover:text-white transition-colors bg-[#141414] rounded-lg border border-[#1F1F1F] hover:bg-[#1F1F1F]"
                      title="Download as PDF"
                    >
                      {downloadingPdf ? <Loader2 className="w-5 h-5 animate-spin" /> : <Download className="w-5 h-5" />}
                    </button>
                  </div>

                  <div className="prose prose-invert max-w-none prose-headings:font-bold prose-headings:text-white prose-p:text-gray-300 prose-code:text-blue-300 prose-pre:bg-[#141414] prose-pre:border prose-pre:border-[#1F1F1F]">
                    <ReactMarkdown>{result}</ReactMarkdown>
                  </div>
                </motion.div>
              ) : (
                <div className="flex flex-col items-center justify-center flex-grow bg-[#0A0A0A] border border-[#1F1F1F] border-dashed rounded-2xl p-10 text-center">
                  <div className="w-16 h-16 bg-[#141414] rounded-full flex items-center justify-center mb-6">
                    <Sparkles className="w-8 h-8 text-gray-600" />
                  </div>
                  <h3 className="text-xl font-bold text-white mb-2">Ready to Explain</h3>
                  <p className="text-gray-500 max-w-sm">
                    Content will appear here. The AI formats explanations with clear headings, code blocks, and key takeaways.
                  </p>
                </div>
              )}
            </AnimatePresence>
          </div>

        </div>
      </div>
    </div>
  );
}
